### ISSUE TITLE
ContactのGoogle Formが表示されない

### ISSUE THREAD

**Issue by Cyndaquil1999** [kstm-su/kstm-su.github.io#18]
スマホで大学アカウントで入ったところ、正常に表示がされてないです
![image](https://github.com/kstm-su/kstm-su.github.io/assets/65232498/32742a05-fa35-49e8-9917-bb2deafa0273)

**Comment by nona-takahara** [comment]
#23 マージ後に見えるか確認

**Comment by nona-takahara** [comment]
解決しないので、リンクにしましょう
