### ISSUE TITLE
GitHub Actionsが動かない

### ISSUE THREAD

**Issue by Nlkomaru** [kstm-su/kstm-su.github.io#22]
os依存のライブラリによって、ciが滑っているため直す必要があり。

参考になるかも
https://blog.chick-p.work/til/resolve-vite-cannot-find-rollup

**Comment by nona-takahara** [comment]
とりあえずいったんは #23 にて package-lock.json と node_modulesを作り直しましたが、これで滑るようなら、Actionsの方のコマンドを`npm install`に変えます。
