### ISSUE TITLE
deployの自動化

### ISSUE THREAD

**Issue by ritsuxis** [kstm-su/kstm-su.github.io#3]
手動デプロイはやはり面倒くさいので、masterへpush (+PRを作成する)と自動でビルドが走るようにしたい  
github actionを使ってgithub内で完結させるほうが楽？かもしれない

**Comment by Cyndaquil1999** [comment]
シェルスクリプトで自動化できるっぽい（CNAME生成も含めて）
https://vuepress.vuejs.org/guide/deploy.html#github-pages

**Comment by nona-takahara** [comment]
GitHub Actionsで行うことにする。CNAMEファイルを置く必要がなくなるかもしれない（参照: <https://docs.github.com/ja/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site> ）。
