### ISSUE TITLE
google formをいい感じに埋め込む

### ISSUE THREAD

**Issue by ritsuxis** [kstm-su/kstm-su.github.io#4]
[contact](https://kstm.shinshu-u.ac.jp/contact.html)のページにあるgoogle formをサイトに合うようにデザインを変更したい。  
具体的にはvueでフォームを作成して、それに対応する質問と属性を拾ってくればどうにかなりそう

参考にできそうなリンク
https://qiita.com/ykoizumi0903/items/9a1bf871f477651817a8

**Comment by nona-takahara** [comment]
リンクで対応することにしたのでいったんクローズにします。
