### ISSUE TITLE
yarnのversionを上げる

### ISSUE THREAD

**Issue by ritsuxis** [kstm-su/kstm-su.github.io#7]
今はyarn v1を使っているが、さすがに古くなってきた

最新はv3らしいのでそちらに上げるかnpmに移行するかしたい

**Comment by nona-takahara** [comment]
メモも兼ねて：現状だとNode.js v20ではビルドができないため、パッケージ管理ツールの更新が必要（暫定でEOLを迎えたv16で動かしている）

**Comment by nona-takahara** [comment]
おそらく、yarn.lockを削除するだけでnpmへの移行が完了するといってもいいかも。npx vuepressにする必要はあるかもしれないが（vuepressのガイドを確認したい）

**Comment by nona-takahara** [comment]
update-to-node22 commit b56bc776 にて対応完了

PR通ったらこのIssueはクローズ
